name: Aqua
on: 
  push:
    branches:
      - master
jobs:
  aqua-scanner:
    uses: argon-gh-demo/github-workflows/.github/workflows/aquasec-scan.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}

  build-docker:
    uses: argon-gh-demo/github-workflows/.github/workflows/build-docker-billy.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
    with:      
      ARTIFACT_PATH: "saargon/graphql-vuln-ext"
      
