name: "Trivy Scan"
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  
permissions: write-all

jobs:
  aqua-workflow:
      uses: argon-gh-test/github-workflows/.github/workflows/aquasec-scan.yml@main
      secrets:
        gh_token: "${{ github.token }}"
        AQUA_KEY: "${{ secrets.AQUA_KEY }}"
        AQUA_SECRET: "${{ secrets.AQUA_SECRET }}"
