name: Aqua
on: 
  push:
    branches:
      - master
jobs:
  aqua-scanner:
    uses: argon-gh-demo/github-workflows/.github/workflows/aquasec-scan.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
