name: Aqua
on: 
  push:
    branches:
      - rb-repro
jobs:
  aqua-scanner:
    uses: argon-gh-demo/github-workflows/.github/workflows/aquasec-scan.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
  
  build-image:
    needs: aqua-scanner
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: "saargon/graphql-vuln-ext:${{ github.sha }}"

  create-manifest:
    needs: build-image
    uses: argon-gh-demo/github-workflows/.github/workflows/billy-ubuntu.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
    with:      
      ARTIFACT_PATH: "saargon/graphql-vuln-ext"
