name: Aqua
on: 
  push:
    branches:
      - master
      
jobs:
  scan-build:
    needs: aqua-scanner
    uses: argon-gh-demo/github-workflows/.github/workflows/aqua-scan-build.yml@main
    secrets: 
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
    with:      
      ARTIFACT_PATH: "saargon/graphql-vuln-ext"
